### PR TITLE
Add wandb integration

### PR DESCRIPTION
**Pull request by vwxyzjn**
Feel free to run 

```
python runner.py --train --file rl_games/configs/atari/ppo_breakout_torch.yaml --track
WANDB_API_KEY=xxxx python runner.py --train --file rl_games/configs/atari/ppo_breakout_torch.yaml --track
python runner.py --train --file rl_games/configs/atari/ppo_breakout_torch.yaml --wandb-project-name rl-games-special-test --track
python runner.py --train --file rl_games/configs/atari/ppo_breakout_torch.yaml --wandb-project-name rl-games-special-test -wandb-entity openrlbenchmark --track
```

### CODE REVIEW

**Comment by vwxyzjn** [comment]
I’d suggest merging poetry first, then I can add the dependencies in this PR and documentation :)

**Comment by Denys88** [comment]
Just merged poetry

**Comment by vwxyzjn** [comment]
Give me a sec.

**Comment by vwxyzjn** [comment]
It's ready. Thanks!

**Pull request merged**
