### PR TITLE
Ad/documentation

### PR DESCRIPTION
**Pull request by anishhdiwan**
Added an explanation of some core classes from rl_games and how they work. Also added a guide on using rl_games for your own work (using a style similar to IsaacGymEnvs). 

@Denys88 I hope this is accurate and helps others easily adapt rl_games to their own work :)

### CODE REVIEW

**Comment by Denys88** [comment]
Reviewing it!

**Comment by anishhdiwan** [comment]
Hey! I'm closing the PR temporarily. I realise that a how-to might not be relevant as "documentation" for the library. I'll try and add some docstrings to the essential parts of the library so that a proper documentation can be made with tools like Sphinx. Let me know if you have any feedback!

**Comment by Denys88** [comment]
Hi @anishhdiwan, it looks good overall. And everything is done in separate in separate doc.
Actually I am happy to merge it as is right now, just need to add a link to the top of README.md.
In a few weeks I can make next release.

**Comment by anishhdiwan** [comment]
Hello @Denys88, that sounds great! I can reopen the PR then. Could you please add the README link (not sure where it'd fit the best)? 

I will also add the docstrings soon and send another PR at a later time. Thanks

**Comment by Denys88** [comment]
Will do it. 
Could you confirm your name please: Anish Diwan? I want to put it near the link or in your doc (up to you), thanks.

**Review by Denys88 — APPROVED** [review]

**Pull request merged**
